### ISSUE TITLE
.jpg required

### ISSUE THREAD

**Issue by wmaiouiru** [rowanwins/geotiff-server#1]
https://github.com/rowanwins/geotiff-server/blob/44c09044fd47845f018ad6332086dfc8a70f0af9/test.html#L28

In the test example here .jpg is needed:
`http://0.0.0.0:5000/tiles/{x}/{y}/{z}.jpg?{sceneId}`

**Comment by rowanwins** [comment]
Yep good pickup thanks @wmaiouiru , AWS gateway is very finickity about those mime types and i wasted a few hours of life on that.

Ideally i eventually want the user to be able to specify jpeg or png as their desired response type
